### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by FranklinChen** [feuerbach/lexer-applicative#1]
The following result hangs:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Language.Lexer.Applicative (tokens)
import Text.Regex.Applicative
import qualified Data.Loc as Loc
import qualified Data.Char as Char

type Token = Integer

token :: RE Char Token
token = "one" *> pure 1

spaces :: RE Char ()
spaces = (many $ psym Char.isSpace) *> pure ()

result :: [Loc.L Token]
result = tokens token spaces "filename" "one -"
```

**Comment by feuerbach** [comment]
This is because you allow empty whitespace. Use `some` instead of `many`.

**Comment by feuerbach** [comment]
On a second thought, we can do better than that. I've just released 1.0.0.1 which correctly reports the lexical error in your example.

**Comment by FranklinChen** [comment]
Ah, oops, I didn't read the API carefully... I'm used to words like `many` meaning "0 or more" and `many1` meaning "1 or more", as in Parsec.

**Comment by feuerbach** [comment]
Right. regex-applicative reuses combinators from Control.Applicative where applicable, and they sometimes differ from the Parsec names.
