### ISSUE TITLE
Is `runLexer` incremental?

### ISSUE THREAD

**Issue by banacorn** [feuerbach/lexer-applicative#7]
Thank you for this lovely work!

As the title, I wonder if `runLexer`, or the whole package in general, is capable of converting a stream of chars into tokens incrementally? 

(looking suspicious!)
https://github.com/feuerbach/lexer-applicative/blob/7905a6373d7f6bd7b85a52f5aa7a12ab2cec2510/src/Language/Lexer/Applicative.hs#L280-L284

**Comment by UnkindPartition** [comment]
> Thank you for this lovely work!

Glad you like it!

> As the title, I wonder if runLexer, or the whole package in general, is capable of converting a stream of chars into tokens incrementally?

Depends on what precisely you mean by "incrementally", but I'd say yes — in the sense that it emits tokens as soon as they are recognized, without consuming the whole input, or any more input than necessary:

``` haskell
import Language.Lexer.Applicative
import Text.Regex.Applicative
import Data.Char

lexer =
  token (longest (psym (not . isSpace))) <>
  whitespace (longest (psym isSpace))

main = do
  -- Normal input
  putStrLn . take 30 . show $ runLexer lexer "-" "a a a"
  -- Infinite input
  putStrLn . take 30 . show $ runLexer lexer "-" (cycle "a ")
  -- Input ending with an error
  putStrLn . take 30 . show $ runLexer lexer "-" ("a a a " ++ undefined)
```

**Comment by banacorn** [comment]
That's great! 
Because I want to feed those tokens to `attoparsec`, otherwise it would defeat the purpose of paring with an incremental parser.
